export const documentsData = [
  {
    "id": "doc-1",
    "title": "Case Study - Automotive Charging System Diagnosis",
    "filename": "Case Study - Automotive Charging System Diagnosis.pdf",
    "path": "assets/docs/Case Study - Automotive Charging System Diagnosis.pdf",
    "extension": "PDF",
    "size": "829.3 KB",
    "category": "ช่างยนต์ / ยานยนต์ไฟฟ้า",
    "categoryId": "automotive",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-2",
    "title": "Electrical Breaker Troubleshooting Guide",
    "filename": "Electrical Breaker Troubleshooting Guide.pdf",
    "path": "assets/docs/Electrical Breaker Troubleshooting Guide.pdf",
    "extension": "PDF",
    "size": "598.3 KB",
    "category": "ช่างไฟฟ้าและอิเล็กทรอนิกส์",
    "categoryId": "electrical",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-3",
    "title": "Executive Academic Management Copilot",
    "filename": "Executive Academic Management Copilot.docx",
    "path": "assets/docs/Executive Academic Management Copilot.docx",
    "extension": "DOCX",
    "size": "44.6 KB",
    "category": "บริหารวิชาการและยุทธศาสตร์",
    "categoryId": "management",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-4",
    "title": "Home Visit Assessment Form (1)",
    "filename": "Home Visit Assessment Form (1).pdf",
    "path": "assets/docs/Home Visit Assessment Form (1).pdf",
    "extension": "PDF",
    "size": "44.1 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-5",
    "title": "Memo_Library_Exhibition",
    "filename": "Memo_Library_Exhibition.pdf",
    "path": "assets/docs/Memo_Library_Exhibition.pdf",
    "extension": "PDF",
    "size": "33.9 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-6",
    "title": "Metrology Evaluation Report",
    "filename": "Metrology Evaluation Report.pdf",
    "path": "assets/docs/Metrology Evaluation Report.pdf",
    "extension": "PDF",
    "size": "677.6 KB",
    "category": "เมคคาทรอนิกส์ / ช่างกล / เชื่อม",
    "categoryId": "mechanical",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-7",
    "title": "Psychomotor Rubric_ HV Disconnection _amp_ Safe De-energization",
    "filename": "Psychomotor Rubric_ HV Disconnection _amp_ Safe De-energization.pdf",
    "path": "assets/docs/Psychomotor Rubric_ HV Disconnection _amp_ Safe De-energization.pdf",
    "extension": "PDF",
    "size": "87.2 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-8",
    "title": "Storyboard สื่อการสอนช่างยนต์ - การเปลี่ยนหัวเทีย",
    "filename": "Storyboard สื่อการสอนช่างยนต์ - การเปลี่ยนหัวเทีย.pdf",
    "path": "assets/docs/Storyboard สื่อการสอนช่างยนต์ - การเปลี่ยนหัวเทีย.pdf",
    "extension": "PDF",
    "size": "528.7 KB",
    "category": "ช่างยนต์ / ยานยนต์ไฟฟ้า",
    "categoryId": "automotive",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-9",
    "title": "Universal Teacher",
    "filename": "Universal Teacher.docx",
    "path": "assets/docs/Universal Teacher.docx",
    "extension": "DOCX",
    "size": "52.0 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-10",
    "title": "Universal_Lifelong_Learning",
    "filename": "Universal_Lifelong_Learning.docx",
    "path": "assets/docs/Universal_Lifelong_Learning.docx",
    "extension": "DOCX",
    "size": "50.6 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-11",
    "title": "VOICE AIวิทยาลัยเทคนิคสุราษฎร์ธานี (3)",
    "filename": "VOICE AIวิทยาลัยเทคนิคสุราษฎร์ธานี (3).docx",
    "path": "assets/docs/VOICE AIวิทยาลัยเทคนิคสุราษฎร์ธานี (3).docx",
    "extension": "DOCX",
    "size": "42.1 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-12",
    "title": "Welding Lab Material Requirement Plan",
    "filename": "Welding Lab Material Requirement Plan.pdf",
    "path": "assets/docs/Welding Lab Material Requirement Plan.pdf",
    "extension": "PDF",
    "size": "256.8 KB",
    "category": "เมคคาทรอนิกส์ / ช่างกล / เชื่อม",
    "categoryId": "mechanical",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-13",
    "title": "antigravity-manual-surat-tech-2026-09-25",
    "filename": "antigravity-manual-surat-tech-2026-09-25.md",
    "path": "assets/docs/antigravity-manual-surat-tech-2026-09-25.md",
    "extension": "MD",
    "size": "172.7 KB",
    "category": "บริหารวิชาการและยุทธศาสตร์",
    "categoryId": "management",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-14",
    "title": "antigravity-manual-surat-tech-2026-09-25",
    "filename": "antigravity-manual-surat-tech-2026-09-25.pdf",
    "path": "assets/docs/antigravity-manual-surat-tech-2026-09-25.pdf",
    "extension": "PDF",
    "size": "3.57 MB",
    "category": "บริหารวิชาการและยุทธศาสตร์",
    "categoryId": "management",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-15",
    "title": "กิจกรรม_ใบงาน_และแบบประเมินภาษาจีน",
    "filename": "กิจกรรม_ใบงาน_และแบบประเมินภาษาจีน.pdf",
    "path": "assets/docs/กิจกรรม_ใบงาน_และแบบประเมินภาษาจีน.pdf",
    "extension": "PDF",
    "size": "673.8 KB",
    "category": "วิชาสามัญสัมพันธ์และภาษา",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-16",
    "title": "คลังข้อสอบวิชาชีพช่างเชื่อมและเฉลย",
    "filename": "คลังข้อสอบวิชาชีพช่างเชื่อมและเฉลย.pdf",
    "path": "assets/docs/คลังข้อสอบวิชาชีพช่างเชื่อมและเฉลย.pdf",
    "extension": "PDF",
    "size": "397.4 KB",
    "category": "เมคคาทรอนิกส์ / ช่างกล / เชื่อม",
    "categoryId": "mechanical",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-17",
    "title": "ความเค้นและความเครียดงานเชื่อม",
    "filename": "ความเค้นและความเครียดงานเชื่อม.pdf",
    "path": "assets/docs/ความเค้นและความเครียดงานเชื่อม.pdf",
    "extension": "PDF",
    "size": "744.0 KB",
    "category": "เมคคาทรอนิกส์ / ช่างกล / เชื่อม",
    "categoryId": "mechanical",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-18",
    "title": "คู่มือการปฏิบัติงานการคัดแยกสินค้าขาเข้",
    "filename": "คู่มือการปฏิบัติงานการคัดแยกสินค้าขาเข้.pdf",
    "path": "assets/docs/คู่มือการปฏิบัติงานการคัดแยกสินค้าขาเข้.pdf",
    "extension": "PDF",
    "size": "1.04 MB",
    "category": "การจัดการโลจิสติกส์",
    "categoryId": "logistics",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-19",
    "title": "คู่มือประเมินและแบบฟอร์มตรวจงานแบตเตอรี",
    "filename": "คู่มือประเมินและแบบฟอร์มตรวจงานแบตเตอรี.pdf",
    "path": "assets/docs/คู่มือประเมินและแบบฟอร์มตรวจงานแบตเตอรี.pdf",
    "extension": "PDF",
    "size": "868.1 KB",
    "category": "ช่างยนต์ / ยานยนต์ไฟฟ้า",
    "categoryId": "automotive",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-20",
    "title": "คู่มือผู้ช่วยวิศวกรและช่างไฟฟ้า_ActionPlanGuide.html",
    "filename": "คู่มือผู้ช่วยวิศวกรและช่างไฟฟ้า_ActionPlanGuide.html.pdf",
    "path": "assets/docs/คู่มือผู้ช่วยวิศวกรและช่างไฟฟ้า_ActionPlanGuide.html.pdf",
    "extension": "PDF",
    "size": "619.9 KB",
    "category": "ช่างไฟฟ้าและอิเล็กทรอนิกส์",
    "categoryId": "electrical",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-21",
    "title": "คู่มือวิเคราะห์และแก้ไขปัญหาสายไฟละลายใ",
    "filename": "คู่มือวิเคราะห์และแก้ไขปัญหาสายไฟละลายใ.pdf",
    "path": "assets/docs/คู่มือวิเคราะห์และแก้ไขปัญหาสายไฟละลายใ.pdf",
    "extension": "PDF",
    "size": "591.5 KB",
    "category": "ช่างไฟฟ้าและอิเล็กทรอนิกส์",
    "categoryId": "electrical",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-22",
    "title": "คู่มือและชุดแบบร่างการดูแลช่วยเหลือนักเ",
    "filename": "คู่มือและชุดแบบร่างการดูแลช่วยเหลือนักเ.pdf",
    "path": "assets/docs/คู่มือและชุดแบบร่างการดูแลช่วยเหลือนักเ.pdf",
    "extension": "PDF",
    "size": "441.1 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-23",
    "title": "คู่มือและแบบฟอร์มการส่งข้อมูลเพื่อพัฒนา",
    "filename": "คู่มือและแบบฟอร์มการส่งข้อมูลเพื่อพัฒนา.pdf",
    "path": "assets/docs/คู่มือและแบบฟอร์มการส่งข้อมูลเพื่อพัฒนา.pdf",
    "extension": "PDF",
    "size": "618.8 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-24",
    "title": "คู่มือและแผนการดำเนินงานระบบดูแลสวัสดิก",
    "filename": "คู่มือและแผนการดำเนินงานระบบดูแลสวัสดิก.pdf",
    "path": "assets/docs/คู่มือและแผนการดำเนินงานระบบดูแลสวัสดิก.pdf",
    "extension": "PDF",
    "size": "729.6 KB",
    "category": "บริหารวิชาการและยุทธศาสตร์",
    "categoryId": "management",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-25",
    "title": "คู่มือใช้งาน SmartIndex-Gov",
    "filename": "คู่มือใช้งาน SmartIndex-Gov.pdf",
    "path": "assets/docs/คู่มือใช้งาน SmartIndex-Gov.pdf",
    "extension": "PDF",
    "size": "349.4 KB",
    "category": "บริหารวิชาการและยุทธศาสตร์",
    "categoryId": "management",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-26",
    "title": "ชุดข้อสอบและใบงานประเมินผลช่างยนต์_สอศ",
    "filename": "ชุดข้อสอบและใบงานประเมินผลช่างยนต์_สอศ.pdf",
    "path": "assets/docs/ชุดข้อสอบและใบงานประเมินผลช่างยนต์_สอศ.pdf",
    "extension": "PDF",
    "size": "902.5 KB",
    "category": "ช่างยนต์ / ยานยนต์ไฟฟ้า",
    "categoryId": "automotive",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-27",
    "title": "ชุดสถานการณ์จำลองการแก้ปัญหางานช่างเทคน",
    "filename": "ชุดสถานการณ์จำลองการแก้ปัญหางานช่างเทคน.pdf",
    "path": "assets/docs/ชุดสถานการณ์จำลองการแก้ปัญหางานช่างเทคน.pdf",
    "extension": "PDF",
    "size": "981.0 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-28",
    "title": "ตารางเรียนและตารางสอน_แผนกวิชาการจัดการโ",
    "filename": "ตารางเรียนและตารางสอน_แผนกวิชาการจัดการโ.pdf",
    "path": "assets/docs/ตารางเรียนและตารางสอน_แผนกวิชาการจัดการโ.pdf",
    "extension": "PDF",
    "size": "426.4 KB",
    "category": "การจัดการโลจิสติกส์",
    "categoryId": "logistics",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-29",
    "title": "รายงานการวิเคราะห์และพัฒนาหลักสูตรรายวิ",
    "filename": "รายงานการวิเคราะห์และพัฒนาหลักสูตรรายวิ.pdf",
    "path": "assets/docs/รายงานการวิเคราะห์และพัฒนาหลักสูตรรายวิ.pdf",
    "extension": "PDF",
    "size": "800.2 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-30",
    "title": "รายงานประเมินความพร้อมโปรเจกต์ - แอปเช็คช",
    "filename": "รายงานประเมินความพร้อมโปรเจกต์ - แอปเช็คช.pdf",
    "path": "assets/docs/รายงานประเมินความพร้อมโปรเจกต์ - แอปเช็คช.pdf",
    "extension": "PDF",
    "size": "712.7 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-31",
    "title": "รายงานประเมินราคาซ่อมและวิเคราะห์ปัญหาเ",
    "filename": "รายงานประเมินราคาซ่อมและวิเคราะห์ปัญหาเ.pdf",
    "path": "assets/docs/รายงานประเมินราคาซ่อมและวิเคราะห์ปัญหาเ.pdf",
    "extension": "PDF",
    "size": "1009.1 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-32",
    "title": "รายงานผลการตรวจวัดและประเมินมุมดอกสว่าน H",
    "filename": "รายงานผลการตรวจวัดและประเมินมุมดอกสว่าน H.pdf",
    "path": "assets/docs/รายงานผลการตรวจวัดและประเมินมุมดอกสว่าน H.pdf",
    "extension": "PDF",
    "size": "686.0 KB",
    "category": "เมคคาทรอนิกส์ / ช่างกล / เชื่อม",
    "categoryId": "mechanical",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-33",
    "title": "รายงานผลการตรวจสอบเอกสารมอบตัว - นายกิตติ",
    "filename": "รายงานผลการตรวจสอบเอกสารมอบตัว - นายกิตติ.pdf",
    "path": "assets/docs/รายงานผลการตรวจสอบเอกสารมอบตัว - นายกิตติ.pdf",
    "extension": "PDF",
    "size": "648.3 KB",
    "category": "บริหารวิชาการและยุทธศาสตร์",
    "categoryId": "management",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-34",
    "title": "รายงานผลการตรวจและวิเคราะห์แบบทดสอบวิชา",
    "filename": "รายงานผลการตรวจและวิเคราะห์แบบทดสอบวิชา.pdf",
    "path": "assets/docs/รายงานผลการตรวจและวิเคราะห์แบบทดสอบวิชา.pdf",
    "extension": "PDF",
    "size": "589.1 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-35",
    "title": "สคริปต์ Infographic 5 เหตุผลที่ต้องเรียนเมคคาทรอน",
    "filename": "สคริปต์ Infographic 5 เหตุผลที่ต้องเรียนเมคคาทรอน.pdf",
    "path": "assets/docs/สคริปต์ Infographic 5 เหตุผลที่ต้องเรียนเมคคาทรอน.pdf",
    "extension": "PDF",
    "size": "616.3 KB",
    "category": "เมคคาทรอนิกส์ / ช่างกล / เชื่อม",
    "categoryId": "mechanical",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-36",
    "title": "สอการสอนวทยาศาสตร เรอง สมดลเคม",
    "filename": "สอการสอนวทยาศาสตร เรอง สมดลเคม.pdf",
    "path": "assets/docs/สอการสอนวทยาศาสตร เรอง สมดลเคม.pdf",
    "extension": "PDF",
    "size": "107.9 KB",
    "category": "วิชาสามัญสัมพันธ์และภาษา",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-37",
    "title": "เกณฑ์การประเมินภาคปฏิบัติ งานบริการตัวถั",
    "filename": "เกณฑ์การประเมินภาคปฏิบัติ งานบริการตัวถั.pdf",
    "path": "assets/docs/เกณฑ์การประเมินภาคปฏิบัติ งานบริการตัวถั.pdf",
    "extension": "PDF",
    "size": "684.3 KB",
    "category": "ช่างยนต์ / ยานยนต์ไฟฟ้า",
    "categoryId": "automotive",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-38",
    "title": "เอกสารนำเสนอและสรุปบทเรียน โลจิสติกส์ ปวช",
    "filename": "เอกสารนำเสนอและสรุปบทเรียน โลจิสติกส์ ปวช.pdf",
    "path": "assets/docs/เอกสารนำเสนอและสรุปบทเรียน โลจิสติกส์ ปวช.pdf",
    "extension": "PDF",
    "size": "199.9 KB",
    "category": "การจัดการโลจิสติกส์",
    "categoryId": "logistics",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-39",
    "title": "เอกสารแนะนำสื่อการสอน_เรื่องการตรวจเช็กแ",
    "filename": "เอกสารแนะนำสื่อการสอน_เรื่องการตรวจเช็กแ.pdf",
    "path": "assets/docs/เอกสารแนะนำสื่อการสอน_เรื่องการตรวจเช็กแ.pdf",
    "extension": "PDF",
    "size": "683.3 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-40",
    "title": "แบบประเมิน IOC เครื่องมือวิจัยช่างยนต์",
    "filename": "แบบประเมิน IOC เครื่องมือวิจัยช่างยนต์.pdf",
    "path": "assets/docs/แบบประเมิน IOC เครื่องมือวิจัยช่างยนต์.pdf",
    "extension": "PDF",
    "size": "599.7 KB",
    "category": "ช่างยนต์ / ยานยนต์ไฟฟ้า",
    "categoryId": "automotive",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-41",
    "title": "แผนการจัดการเรียนรู้ฐานสมรรถนะ",
    "filename": "แผนการจัดการเรียนรู้ฐานสมรรถนะ.pdf",
    "path": "assets/docs/แผนการจัดการเรียนรู้ฐานสมรรถนะ.pdf",
    "extension": "PDF",
    "size": "645.9 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-42",
    "title": "แผนการจัดการเรียนรู้ฐานสมรรถนะ_นิวแมติกส",
    "filename": "แผนการจัดการเรียนรู้ฐานสมรรถนะ_นิวแมติกส.pdf",
    "path": "assets/docs/แผนการจัดการเรียนรู้ฐานสมรรถนะ_นิวแมติกส.pdf",
    "extension": "PDF",
    "size": "670.9 KB",
    "category": "เมคคาทรอนิกส์ / ช่างกล / เชื่อม",
    "categoryId": "mechanical",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-43",
    "title": "แผนการจัดการเรียนรู้มุ่งเน้นสมรรถนะ - การ",
    "filename": "แผนการจัดการเรียนรู้มุ่งเน้นสมรรถนะ - การ.pdf",
    "path": "assets/docs/แผนการจัดการเรียนรู้มุ่งเน้นสมรรถนะ - การ.pdf",
    "extension": "PDF",
    "size": "672.3 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-44",
    "title": "แผนการจัดการเรียนรู้มุ่งเน้นสมรรถนะ_งานเ",
    "filename": "แผนการจัดการเรียนรู้มุ่งเน้นสมรรถนะ_งานเ.pdf",
    "path": "assets/docs/แผนการจัดการเรียนรู้มุ่งเน้นสมรรถนะ_งานเ.pdf",
    "extension": "PDF",
    "size": "584.1 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-45",
    "title": "แผนกิจกรรมเกมภาษาจีน_จังหวะตลาด_多少钱",
    "filename": "แผนกิจกรรมเกมภาษาจีน_จังหวะตลาด_多少钱.pdf",
    "path": "assets/docs/แผนกิจกรรมเกมภาษาจีน_จังหวะตลาด_多少钱.pdf",
    "extension": "PDF",
    "size": "950.3 KB",
    "category": "วิชาสามัญสัมพันธ์และภาษา",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-46",
    "title": "โครงสร้างรายวิชาเครื่องมือกลเบื้องต้น_ปว",
    "filename": "โครงสร้างรายวิชาเครื่องมือกลเบื้องต้น_ปว.pdf",
    "path": "assets/docs/โครงสร้างรายวิชาเครื่องมือกลเบื้องต้น_ปว.pdf",
    "extension": "PDF",
    "size": "833.0 KB",
    "category": "เมคคาทรอนิกส์ / ช่างกล / เชื่อม",
    "categoryId": "mechanical",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-47",
    "title": "ใบความรู้ มอเตอร์ไฟฟ้ากระแสสลับ 1 เฟส และ 3 เ",
    "filename": "ใบความรู้ มอเตอร์ไฟฟ้ากระแสสลับ 1 เฟส และ 3 เ.pdf",
    "path": "assets/docs/ใบความรู้ มอเตอร์ไฟฟ้ากระแสสลับ 1 เฟส และ 3 เ.pdf",
    "extension": "PDF",
    "size": "1.30 MB",
    "category": "ช่างไฟฟ้าและอิเล็กทรอนิกส์",
    "categoryId": "electrical",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-48",
    "title": "ใบความรู้มาตรฐานอาชีวศึกษา 2567",
    "filename": "ใบความรู้มาตรฐานอาชีวศึกษา 2567.pdf",
    "path": "assets/docs/ใบความรู้มาตรฐานอาชีวศึกษา 2567.pdf",
    "extension": "PDF",
    "size": "696.9 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-49",
    "title": "ใบความรู้ระบบจัดการแบตเตอรี่ (BMS)",
    "filename": "ใบความรู้ระบบจัดการแบตเตอรี่ (BMS).pdf",
    "path": "assets/docs/ใบความรู้ระบบจัดการแบตเตอรี่ (BMS).pdf",
    "extension": "PDF",
    "size": "104.0 KB",
    "category": "ช่างยนต์ / ยานยนต์ไฟฟ้า",
    "categoryId": "automotive",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-50",
    "title": "ใบงาน Verb to Be",
    "filename": "ใบงาน Verb to Be.pdf",
    "path": "assets/docs/ใบงาน Verb to Be.pdf",
    "extension": "PDF",
    "size": "71.2 KB",
    "category": "วิชาสามัญสัมพันธ์และภาษา",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-51",
    "title": "ใบงานคณิตศาสตร์เชิงช่าง เรื่อง อนุพันธ์แล",
    "filename": "ใบงานคณิตศาสตร์เชิงช่าง เรื่อง อนุพันธ์แล.pdf",
    "path": "assets/docs/ใบงานคณิตศาสตร์เชิงช่าง เรื่อง อนุพันธ์แล.pdf",
    "extension": "PDF",
    "size": "803.4 KB",
    "category": "วิชาสามัญสัมพันธ์และภาษา",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-52",
    "title": "ใบงานที่ 5 การควบคุมระบบสายพานคัดแยกชิ้นง",
    "filename": "ใบงานที่ 5 การควบคุมระบบสายพานคัดแยกชิ้นง.pdf",
    "path": "assets/docs/ใบงานที่ 5 การควบคุมระบบสายพานคัดแยกชิ้นง.pdf",
    "extension": "PDF",
    "size": "770.4 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-53",
    "title": "ใบงานปฏิบัติการ IT-LabCraft Pro",
    "filename": "ใบงานปฏิบัติการ IT-LabCraft Pro.pdf",
    "path": "assets/docs/ใบงานปฏิบัติการ IT-LabCraft Pro.pdf",
    "extension": "PDF",
    "size": "881.2 KB",
    "category": "วิชาการทั่วไปและเกณฑ์ประเมิน",
    "categoryId": "general",
    "badge": "Learning Artifact"
  },
  {
    "id": "doc-54",
    "title": "ใบงานปฏิบัติการที่ 3 - การใช้มัลติมิเตอร์แบ",
    "filename": "ใบงานปฏิบัติการที่ 3 - การใช้มัลติมิเตอร์แบ.pdf",
    "path": "assets/docs/ใบงานปฏิบัติการที่ 3 - การใช้มัลติมิเตอร์แบ.pdf",
    "extension": "PDF",
    "size": "572.9 KB",
    "category": "ช่างไฟฟ้าและอิเล็กทรอนิกส์",
    "categoryId": "electrical",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-55",
    "title": "ใบงานปฏิบัติงาน_งานเครื่องยนต์เล็ก",
    "filename": "ใบงานปฏิบัติงาน_งานเครื่องยนต์เล็ก.pdf",
    "path": "assets/docs/ใบงานปฏิบัติงาน_งานเครื่องยนต์เล็ก.pdf",
    "extension": "PDF",
    "size": "563.6 KB",
    "category": "ช่างยนต์ / ยานยนต์ไฟฟ้า",
    "categoryId": "automotive",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-56",
    "title": "ใบงานและแบบทดสอบช่างยนต์",
    "filename": "ใบงานและแบบทดสอบช่างยนต์.pdf",
    "path": "assets/docs/ใบงานและแบบทดสอบช่างยนต์.pdf",
    "extension": "PDF",
    "size": "352.9 KB",
    "category": "ช่างยนต์ / ยานยนต์ไฟฟ้า",
    "categoryId": "automotive",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-57",
    "title": "ใบปฏิบัติงาน_วงจรอนุกรม_ปวช2.html",
    "filename": "ใบปฏิบัติงาน_วงจรอนุกรม_ปวช2.html.pdf",
    "path": "assets/docs/ใบปฏิบัติงาน_วงจรอนุกรม_ปวช2.html.pdf",
    "extension": "PDF",
    "size": "634.4 KB",
    "category": "ช่างไฟฟ้าและอิเล็กทรอนิกส์",
    "categoryId": "electrical",
    "badge": "ค.ศ.4 Evidence"
  },
  {
    "id": "doc-58",
    "title": "ใบเนื้อหา ระบบฉีดเชื้อเพลิงคอมมอนเรล Toyota Hilux",
    "filename": "ใบเนื้อหา ระบบฉีดเชื้อเพลิงคอมมอนเรล Toyota Hilux.pdf",
    "path": "assets/docs/ใบเนื้อหา ระบบฉีดเชื้อเพลิงคอมมอนเรล Toyota Hilux.pdf",
    "extension": "PDF",
    "size": "799.8 KB",
    "category": "ช่างยนต์ / ยานยนต์ไฟฟ้า",
    "categoryId": "automotive",
    "badge": "ค.ศ.4 Evidence"
  }
];
